spring:
  datasource:
    url: 'jdbc:postgresql://${POSTGRES_HOSTNAME}:5432/${POSTGRES_DB}'
    username: '${POSTGRES_USER}'
    password: '${POSTGRES_PASSWORD}'
  jpa:
    hibernate:
      ddl-auto: update
